# Generated by Django 3.2.12 on 2022-03-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Symbol', models.CharField(max_length=30)),
                ('USD', models.CharField(max_length=30)),
            ],
        ),
    ]
