# Generated by Django 3.2.12 on 2022-03-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220308_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='Web',
            field=models.CharField(default='Webside', max_length=30),
        ),
    ]
