# Generated by Django 3.2.12 on 2022-03-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_coins_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='Web',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
