# Generated by Django 3.2.12 on 2022-03-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_coins_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
