# Generated by Django 3.2.12 on 2022-03-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coins_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='Symbol',
        ),
        migrations.RemoveField(
            model_name='coins',
            name='Web',
        ),
    ]
