# Generated by Django 3.2.12 on 2022-03-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220309_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='web',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
