# Generated by Django 3.2.12 on 2022-03-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_coins_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='name',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='coins',
            name='web',
        ),
    ]
