# Generated by Django 3.2.12 on 2022-03-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_data_coins_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatCoins',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Fiats', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
