# Generated by Django 3.2.12 on 2022-03-12 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_fiatcoins'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='Fiat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.fiatcoins'),
        ),
    ]
